rest:
  endpoint:
    fashion: "http://fashion-service.shoppingdemo:8082/fashion/bestseller"
    toys: "http://toys-service.shoppingdemo:8081/toys/bestseller"
    hotdeals: "http://hotdeals-service.shoppingdemo:8083/hotdeals"