apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shoppingdemo
  name: admin-pod
  labels:
    app: shoppingdemo
    type: spring-boot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: admin
      containers:
        - image: joshiste/admin:sio-bcn
          imagePullPolicy: Never
          name: admin
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: spring.boot.admin.ui.brand
              value: <img src="assets/img/icon-spring-boot-admin.svg"><span>SBA $(KUBERNETES_NAMESPACE)</span>
            - name: spring.boot.admin.ui.title
              value: SBA - $(KUBERNETES_NAMESPACE)
            - name: management.server.port
              value: "9080"
            - name: management.endpoints.web.exposure.include
              value: "*"
            - name: management.endpoint.health.show-details
              value: "always"
            - name: spring.cloud.kubernetes.discovery.primary-port-name
              value: "management"
          ports:
            - containerPort: 8080
            - containerPort: 9080
          resources: {}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9080
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: admin




