apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shoppingdemo
  name: toys-pod
  labels:
    app: shoppingdemo
    type: spring-boot
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: toys
    spec:
      containers:
      - image: joshiste/bestseller-toys:chaos-ws-k8s
        imagePullPolicy: Never
        name: toys
        env:
          - name: management.endpoints.web.exposure.include
            value: "*"
        ports:
        - containerPort: 8081
        resources: {}
        readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: toys
