server:
  port: 8082

management:
  endpoint:
    chaosmonkey:
      enabled: true
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: true
spring:
  profiles:
    active: chaos-monkey
  application:
    name: fashion
  zipkin:
    base-url: http://jaeger-server:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  jmx:
    enabled: false